# Reference: 
# https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/
# https://github.com/peter-evans/dockerhub-description

name: docker-image-readme-xray-tproxy
concurrency: deploy-${{ github.workflow }}

on: 
  push:
    branches:
      - main
    paths:
      - xray-tproxy/README.md
env:
  README_FOLDER: xray-tproxy
  REGISTRY_IMAGE: ${{ github.repository_owner }}/xray-tproxy

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REGISTRY_IMAGE }}
          readme-filepath: ${{ env.README_FOLDER }}/README.md
